#!/bin/bash
set -e
CERTCHECK_CONF=${CERTCHECK_CONF-$HOME/.certcheck.conf}

host=$1
[ ! -z "$host" ]

synology_hostname=$(git config -f $CERTCHECK_CONF --get cert.$host.synology-hostname)
synology_hostname=${synology_hostname:-root@$host}
[ ! -z "$synology_hostname" ]

lego_path=$(git config -f $CERTCHECK_CONF --get lego.path)
lego_path=${lego_path:-$HOME/.lego}
[ ! -z "$lego_path" ]

set -x
scp $lego_path/certificates/$host.key root@$host:/usr/syno/etc/certificate/system/default/privkey.pem
(cat $lego_path/certificates/$host.crt; cat $lego_path/certificates/$host.issuer.crt) |\
    ssh $synology_hostname /bin/sh -c '"cat > /usr/syno/etc/certificate/system/default/fullchain.pem"'
ssh $synology_hostname /bin/sh -c '"echo exit 0 > /usr/syno/bin/mkcert"'
ssh $synology_hostname initctl restart nginx
